name: Unpack XNB

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - '**/*.xnb'
      - '.github/workflows/build.yml'

jobs:
  unpack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Clone xnbcli
        run: git clone https://github.com/LeonBlade/xnbcli.git xnbcli-tool

      - name: Install xnbcli dependencies
        run: |
          cd xnbcli-tool
          npm install

      - name: Prepare packed folder
        run: |
          mkdir -p xnbcli-tool/packed
          find . -type f -iname "*.xnb" -exec cp {} xnbcli-tool/packed/ \;

      - name: Check if XNB files exist
        run: |
          if [ -z "$(find xnbcli-tool/packed -maxdepth 1 -type f -iname '*.xnb' -print -quit)" ]; then
            echo "No .xnb files found. Exiting."
            exit 1
          fi

      - name: Unpack XNB files
        run: |
          cd xnbcli-tool
          node xnbcli unpack packed unpacked

      - name: Upload unpacked result
        uses: actions/upload-artifact@v4
        with:
          name: unpacked-maps
          path: xnbcli-tool/unpacked/
