name: Unpack XNB

on:
  workflow_dispatch:
  push:
    paths:
      - '**.xnb'

jobs:
  unpack:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Clone xnbcli
        run: git clone https://github.com/LeonBlade/xnbcli.git xnbcli-tool

      - name: Install xnbcli dependencies
        run: |
          cd xnbcli-tool
          npm install

      - name: Prepare packed folder
        run: |
          mkdir -p xnbcli-tool/packed
          find . -maxdepth 3 -iname "*.xnb" -exec cp {} xnbcli-tool/packed/ \;

      - name: Unpack XNB files
        run: |
          cd xnbcli-tool
          node xnbcli unpack packed unpacked

      - name: Upload unpacked result
        uses: actions/upload-artifact@v4
        with:
          name: unpacked-maps
          path: xnbcli-tool/unpacked/
